### ISSUE TITLE
How to declare just the image button in the RTE toolbar?

### ISSUE THREAD

**Issue by fsuter** [netresearch/t3x-rte_ckeditor_image#141]
Thanks for this extension! I'm trying to use it in a setup where I have my own, rather complete RTE configuration. In particular, this configuration redefines the whole toolbar like so:
```
editor:
    config:
        contentsCss: "EXT:catalog_package/Resources/Public/RTE/rte.css"
        toolbar:
            - [ 'Format', 'Styles' ]
            - [ 'Link', 'Unlink', 'Anchor', 'SpecialChar' ]
            - [ 'NumberedList', 'BulletedList', 'Indent', 'Outdent', 'JustifyLeft', 'JustifyCenter', 'JustifyBlock']
            - [ 'Undo', 'Redo', 'ShowBlocks' ]
            - "/"
            - [ 'Bold', 'Italic', 'Underline', 'Subscript', 'Superscript', 'Table']
```
I have added:
```
editor:
  removePlugins: null
```
to my configuration, but it is not enough, because of my strictly defined toolbar. I tried just adding `, 'Image'` after `'Table'` but that doesn't work. Is `Image` the right button name? If not, which button name should I use? Or is it some other issue?

Thanks in advance for any hint.
