### ISSUE TITLE
[BUG - or Config Problem] <img... gets deleted after save

### ISSUE THREAD

**Issue by grimmcreative** [netresearch/t3x-rte_ckeditor_image#22]
Everything works fine, but when i press save image gets deleted :(

**Comment by prdt3e** [comment]
Where is a save button?
What type of Typo3/t3x-rte_ckeditor_image Version?
More information pls.

**Comment by TimoWinkler** [comment]
I encountered the same problem in typo3 8.7.8
The Problem was detected when saving the page. The image itself was present in plain html but got removed on saving the page.

The plain html that was not saved:
<p><img data-htmlarea-file-table="sys_file" data-htmlarea-file-uid="415" height="1061" src="../fileadmin/user_upload/098dsfsa0993.jpg" width="3840" /></p>

Configuration:
 - Default.yaml: 
   imports:
    - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }
PageTS:
   - RTE.default.buttons.image.options.magic {
    maxWidth = 3000  # Default: 300
    maxHeight = 1000  # Default: 1000
    }

-> t3x-rte_ckeditor_image version:
"name": "netresearch/rte-ckeditor-image",
"version": "v8.7.4",

**Comment by grimmcreative** [comment]
If this issue occurs, search for Configuration that restricts the use of img tag inside the RTE/CKEDITOR.

**Comment by shuffgy** [comment]
@grimmcreative can you give me a hint where i have to look for this configuration? On save the img-tag is removed by typo3. Here is my .yaml

```
# Load default processing options
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:
  config:

    format_tags: "p;h1;h2;h3;h4;h5;pre"

    toolbarGroups:
      - { name: styles, groups: [ styles, format ] }
      - { name: basicstyles, groups: [ basicstyles ] }
      - { name: paragraph, groups: [ list, indent, blocks, align ] }
      - { name: links, groups: [ links ] }
      - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
      - { name: editing, groups: [ spellchecker ] }
      - { name: insert, groups: [ insert ] }
      - { name: tools, groups: [ table, specialchar ] }
      - { name: document, groups: [ mode ] }

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify

    removePlugins: null

    extraAllowedContent:
      - img[!src,alt,width,height]

    removeButtons:
      - Anchor
      - Underline
      - Strike
      - Styles
  externalPlugins:
    typo3image:
      allowedExtensions: "jpg,jpeg,png"
```
