### ISSUE TITLE
Typo3 v12.4 / PHP 8.2 - Extension not working

### ISSUE THREAD

**Issue by Denneee** [netresearch/t3x-rte_ckeditor_image#273]
**Bug description**
I did everything the instructions said, but the picture button in the text editor isn't appearing.

**Steps to reproduce**

1. Install the extension via composer
2. Add a preset for rte_ckeditor in custom Default.yaml
3. Include extension Static Template file

**Screenshots or logs**
My Default.yaml looks like this:

```

imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
    - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }

# Minimal configuration for the editor
editor:
    config:
        removePlugins: null
        height: 300
        width: 'auto'
        ui:
            poweredBy:
                position: 'inside'
                side: 'right'
                label: ''
        htmlSupport:
            allow:
                # Allow any class or any data attribute in any (configured) tag
                - { classes: true, attributes: { pattern: 'data-.+' } }
        # the CSS file to be used inside the editor
        contentsCss:
            - 'EXT:provider/Resources/Public/main/css/editor.min.css?v114'
        toolbar:
            items:
                - sourceEditing
                - removeFormat
                - undo
                - redo
                - '|'
                - selectAll
                - '|'
                - link
                - insertTable
                - tableColumn
                - tableRow
                - mergeTableCells
                - '|'
                - sourceEditing
                - horizontalLine
                # line break
                - '|'
                - bold
                - italic
                - subscript
                - superscript
                - softhyphen
                - '|'
                - bulletedList
                - numberedList
                - blockQuote
                - indent
                - outdent
                - alignment
                - '|'
                - specialCharacters
                - '-'
                - style
                - heading

        stylesSet:
            # block level styles
            - { name: "Referenz", element: "sup", attributes: { class: "ap-inline-reference" } }
            - { name: "Beschreibung", element: "p", attributes: { class: "ap-caption" } }
            - { name: "Eyebrow", element: "p", attributes: { class: "ap-eyebrow" } }
            - { name: "Paragraph Large", element: "p", attributes: { class: "text-lg" } }
            - { name: "Paragraph Small", element: "p", attributes: { class: "text-xs" } }
            - { name: "Primary Button", element: "a", attributes: { class: "ap-btn ap-btn--primary" } }
            - { name: "Secondary Button", element: "a", attributes: { class: "ap-btn ap-btn--secondary" } }
            - { name: "Button Large", element: "a", attributes: { class: "ap-btn--lg" } }
            - { name: "Button Small", element: "a", attributes: { class: "ap-btn--sm" } }
            - { name: "Empty table head", element: "th", attributes: { class: "ap-table-empty" } }

        format_tags: "p;h1;h2;h3;h4;h5;h6"
```

___________________________________________________________________

Here Image how the RTE is looking

![Bildschirmfoto vom 2024-02-26 10-57-55](https://github.com/netresearch/t3x-rte_ckeditor_image/assets/50653159/bd0c11c6-0858-4105-959a-ac5c8f520fa0)
