### ISSUE TITLE
Adding the plugin in a TYPO3 12 instance

### ISSUE THREAD

**Issue by fsuter** [netresearch/t3x-rte_ckeditor_image#283]
**Question**
I am currently migrating a TYPO3 instance from 11 to 12. Adding the plugin to the RTE worked flawlessly with TYPO3 11. With TYPO3 12, I just can't make it: the button for inserting images does not appear in the toolbar.

**Additional information**
This is the configuration preset that I use (again, it worked fine with TYPO3 11):
```yaml
imports:
  - { resource: 'EXT:catalog_resources/Configuration/RTE/Standard.yaml' }
  - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }

editor:
  externalPlugins:
    liststyle:
      resource: "EXT:rte_ckeditor/Resources/Public/JavaScript/Contrib/plugins/liststyle/plugin.js"
  config:
    removePlugins: null
    toolbar:
      - [ 'Image' ]
    extraPlugins:
      - liststyle
```
I have tried adding explicitly the "Image" button in the toolbar, but it doesn't change a thing. I'm not even sure that this is really the button's name.

**Environment**
 - TYPO3 version: 12.4.14
 - PHP version: 8.2
 - Extension version: 12.0.1

**Documentation**
Have you checked the readme/documentation?
- [x] Yes, but I couldn't find anything helpful

**Comment by the-andyman** [comment]
Try insertImage instead of Image in the toolbar.

**Comment by fsuter** [comment]
Thanks for the hint. It is indeed "insertImage" rather than "Image".

There was also an issue with my toolbar configuration. It needs to be:

```yaml
    toolbar:
      items:
        - '|'
        - insertImage
```
